server:
  port: 8081

application:
  name: @project.name@
  description: @project.description@
  version: @project.version@

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/db_rotten_itaumatoes?createDatabaseIfNotExist=true&connectionTimeZone=UTC"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
  cache:
    redis:
      host: "localhost"
      port: 6379
      cache-null-values: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#config:
#  redis:
#    loginAttemps:
#      ttl: 300000

security:
  login:
    maxAttempts: 3
  jwt:
    secret: "bVps6IafGVXz5OeLBuBbBQYctOcjT70BG2hEjeRuJ3Hgpnti1f6uAkA3EM4ZxaV"
